java_library(
    name = "codecompletion",
    srcs = glob(["java/com/google/codecompletion/*.java"]),
    deps = [":org_eclipse_lsp4j"],
)

java_import(
    name = "org_eclipse_lsp4j",
    jars = [
        "lsp4j/org.eclipse.lsp4j-0.3.0.jar",
    ],
)
